### ISSUE TITLE
Font-size has no effect

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#38]
Changing font-size works in the current instance but on restart is reverted to 9pt even though the settings view still says 12.

**Comment by stirno** [comment]
I can't repro this at all :(

**Comment by Buildstarted** [comment]
![Sample](https://jabbrlive.blob.core.windows.net/jabbr-uploads/scrawl-font_228b.gif)

**Comment by pauljz** [comment]
I think the underlying issue is fixed in build 219. (Reopen this if not though!)

A bunch of places in the UI (almost all of them right now) use a slightly smaller size than the one you explicitly set. When the font size was updated we were accidentally using the larger size instead of the smaller size for the File Explorer.

So for now, the size you select may be misleading, but it'll at least be consistent. Will think about splitting it out into two different settings, or at least having something to show the smaller size in the settings dialog, so it's clearer what's going on.

**Comment by Buildstarted** [comment]
The changing size is fixed in this update. Your explanation for what is going on makes sense though.
