### ISSUE TITLE
Highlight the active window

### ISSUE THREAD

**Issue by Buildstarted** [fluentCODE/ScrawlIssues#55]
When it multi-window mode the currently focused window is not highlighted and it makes it difficult to determine while file you're editing. Maybe just a tab highlight?

**Comment by pauljz** [comment]
We're going to try to accomplish this with status bars. Rather than having an application-wide status bar, we'll have a status bar tied to each split editor. The focused editor's bar will be fairly brightly colored, and the others will all be dimmed, which should provide a clear visual indicator as to which one is active.

**Comment by stirno** [comment]
Additionally the cursor only shows in the active window. As @pauljz said it'll be even more obvious once we have the editor statusbar impl, in backlog here: https://github.com/fluentCODE/ScrawlBacklog/issues/9
